/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutStartspotifyImport } from './routes/_layout/startspotify'
import { Route as LayoutProjectsImport } from './routes/_layout/projects'
import { Route as LayoutDetailImport } from './routes/_layout/detail'
import { Route as LayoutBlogImport } from './routes/_layout/blog'
import { Route as LayoutAboutImport } from './routes/_layout/about'
import { Route as LayoutProjectsKetekuImport } from './routes/_layout/projects_/keteku'
import { Route as LayoutProjectsCraveImport } from './routes/_layout/projects_/crave'
import { Route as LayoutProjectsAddImport } from './routes/_layout/projects_/add'
import { Route as LayoutProjectsIdImport } from './routes/_layout/projects_/$id'
import { Route as LayoutProjectsDetailsIndexImport } from './routes/_layout/projects_/details/index'
import { Route as LayoutProjectsDetailsUpdateIdImport } from './routes/_layout/projects_/details/update/$id'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStartspotifyRoute = LayoutStartspotifyImport.update({
  id: '/startspotify',
  path: '/startspotify',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsRoute = LayoutProjectsImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDetailRoute = LayoutDetailImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutBlogRoute = LayoutBlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsKetekuRoute = LayoutProjectsKetekuImport.update({
  id: '/projects_/keteku',
  path: '/projects/keteku',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsCraveRoute = LayoutProjectsCraveImport.update({
  id: '/projects_/crave',
  path: '/projects/crave',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsAddRoute = LayoutProjectsAddImport.update({
  id: '/projects_/add',
  path: '/projects/add',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsIdRoute = LayoutProjectsIdImport.update({
  id: '/projects_/$id',
  path: '/projects/$id',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProjectsDetailsIndexRoute = LayoutProjectsDetailsIndexImport.update(
  {
    id: '/projects_/details/',
    path: '/projects/details/',
    getParentRoute: () => LayoutRoute,
  } as any,
)

const LayoutProjectsDetailsUpdateIdRoute =
  LayoutProjectsDetailsUpdateIdImport.update({
    id: '/projects_/details/update/$id',
    path: '/projects/details/update/$id',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/blog': {
      id: '/_layout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof LayoutBlogImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/detail': {
      id: '/_layout/detail'
      path: '/detail'
      fullPath: '/detail'
      preLoaderRoute: typeof LayoutDetailImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects': {
      id: '/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/startspotify': {
      id: '/_layout/startspotify'
      path: '/startspotify'
      fullPath: '/startspotify'
      preLoaderRoute: typeof LayoutStartspotifyImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects_/$id': {
      id: '/_layout/projects_/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof LayoutProjectsIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects_/add': {
      id: '/_layout/projects_/add'
      path: '/projects/add'
      fullPath: '/projects/add'
      preLoaderRoute: typeof LayoutProjectsAddImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects_/crave': {
      id: '/_layout/projects_/crave'
      path: '/projects/crave'
      fullPath: '/projects/crave'
      preLoaderRoute: typeof LayoutProjectsCraveImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects_/keteku': {
      id: '/_layout/projects_/keteku'
      path: '/projects/keteku'
      fullPath: '/projects/keteku'
      preLoaderRoute: typeof LayoutProjectsKetekuImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects_/details/': {
      id: '/_layout/projects_/details/'
      path: '/projects/details'
      fullPath: '/projects/details'
      preLoaderRoute: typeof LayoutProjectsDetailsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/projects_/details/update/$id': {
      id: '/_layout/projects_/details/update/$id'
      path: '/projects/details/update/$id'
      fullPath: '/projects/details/update/$id'
      preLoaderRoute: typeof LayoutProjectsDetailsUpdateIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutBlogRoute: typeof LayoutBlogRoute
  LayoutDetailRoute: typeof LayoutDetailRoute
  LayoutProjectsRoute: typeof LayoutProjectsRoute
  LayoutStartspotifyRoute: typeof LayoutStartspotifyRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProjectsIdRoute: typeof LayoutProjectsIdRoute
  LayoutProjectsAddRoute: typeof LayoutProjectsAddRoute
  LayoutProjectsCraveRoute: typeof LayoutProjectsCraveRoute
  LayoutProjectsKetekuRoute: typeof LayoutProjectsKetekuRoute
  LayoutProjectsDetailsIndexRoute: typeof LayoutProjectsDetailsIndexRoute
  LayoutProjectsDetailsUpdateIdRoute: typeof LayoutProjectsDetailsUpdateIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutBlogRoute: LayoutBlogRoute,
  LayoutDetailRoute: LayoutDetailRoute,
  LayoutProjectsRoute: LayoutProjectsRoute,
  LayoutStartspotifyRoute: LayoutStartspotifyRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProjectsIdRoute: LayoutProjectsIdRoute,
  LayoutProjectsAddRoute: LayoutProjectsAddRoute,
  LayoutProjectsCraveRoute: LayoutProjectsCraveRoute,
  LayoutProjectsKetekuRoute: LayoutProjectsKetekuRoute,
  LayoutProjectsDetailsIndexRoute: LayoutProjectsDetailsIndexRoute,
  LayoutProjectsDetailsUpdateIdRoute: LayoutProjectsDetailsUpdateIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/blog': typeof LayoutBlogRoute
  '/detail': typeof LayoutDetailRoute
  '/projects': typeof LayoutProjectsRoute
  '/startspotify': typeof LayoutStartspotifyRoute
  '/': typeof LayoutIndexRoute
  '/projects/$id': typeof LayoutProjectsIdRoute
  '/projects/add': typeof LayoutProjectsAddRoute
  '/projects/crave': typeof LayoutProjectsCraveRoute
  '/projects/keteku': typeof LayoutProjectsKetekuRoute
  '/projects/details': typeof LayoutProjectsDetailsIndexRoute
  '/projects/details/update/$id': typeof LayoutProjectsDetailsUpdateIdRoute
}

export interface FileRoutesByTo {
  '/about': typeof LayoutAboutRoute
  '/blog': typeof LayoutBlogRoute
  '/detail': typeof LayoutDetailRoute
  '/projects': typeof LayoutProjectsRoute
  '/startspotify': typeof LayoutStartspotifyRoute
  '/': typeof LayoutIndexRoute
  '/projects/$id': typeof LayoutProjectsIdRoute
  '/projects/add': typeof LayoutProjectsAddRoute
  '/projects/crave': typeof LayoutProjectsCraveRoute
  '/projects/keteku': typeof LayoutProjectsKetekuRoute
  '/projects/details': typeof LayoutProjectsDetailsIndexRoute
  '/projects/details/update/$id': typeof LayoutProjectsDetailsUpdateIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/blog': typeof LayoutBlogRoute
  '/_layout/detail': typeof LayoutDetailRoute
  '/_layout/projects': typeof LayoutProjectsRoute
  '/_layout/startspotify': typeof LayoutStartspotifyRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/projects_/$id': typeof LayoutProjectsIdRoute
  '/_layout/projects_/add': typeof LayoutProjectsAddRoute
  '/_layout/projects_/crave': typeof LayoutProjectsCraveRoute
  '/_layout/projects_/keteku': typeof LayoutProjectsKetekuRoute
  '/_layout/projects_/details/': typeof LayoutProjectsDetailsIndexRoute
  '/_layout/projects_/details/update/$id': typeof LayoutProjectsDetailsUpdateIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/blog'
    | '/detail'
    | '/projects'
    | '/startspotify'
    | '/'
    | '/projects/$id'
    | '/projects/add'
    | '/projects/crave'
    | '/projects/keteku'
    | '/projects/details'
    | '/projects/details/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/blog'
    | '/detail'
    | '/projects'
    | '/startspotify'
    | '/'
    | '/projects/$id'
    | '/projects/add'
    | '/projects/crave'
    | '/projects/keteku'
    | '/projects/details'
    | '/projects/details/update/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/about'
    | '/_layout/blog'
    | '/_layout/detail'
    | '/_layout/projects'
    | '/_layout/startspotify'
    | '/_layout/'
    | '/_layout/projects_/$id'
    | '/_layout/projects_/add'
    | '/_layout/projects_/crave'
    | '/_layout/projects_/keteku'
    | '/_layout/projects_/details/'
    | '/_layout/projects_/details/update/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/about",
        "/_layout/blog",
        "/_layout/detail",
        "/_layout/projects",
        "/_layout/startspotify",
        "/_layout/",
        "/_layout/projects_/$id",
        "/_layout/projects_/add",
        "/_layout/projects_/crave",
        "/_layout/projects_/keteku",
        "/_layout/projects_/details/",
        "/_layout/projects_/details/update/$id"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout/about.tsx",
      "parent": "/_layout"
    },
    "/_layout/blog": {
      "filePath": "_layout/blog.tsx",
      "parent": "/_layout"
    },
    "/_layout/detail": {
      "filePath": "_layout/detail.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects": {
      "filePath": "_layout/projects.tsx",
      "parent": "/_layout"
    },
    "/_layout/startspotify": {
      "filePath": "_layout/startspotify.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects_/$id": {
      "filePath": "_layout/projects_/$id.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects_/add": {
      "filePath": "_layout/projects_/add.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects_/crave": {
      "filePath": "_layout/projects_/crave.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects_/keteku": {
      "filePath": "_layout/projects_/keteku.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects_/details/": {
      "filePath": "_layout/projects_/details/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/projects_/details/update/$id": {
      "filePath": "_layout/projects_/details/update/$id.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
